[[configure_byteman_for_use_with_the_quickstarts]]
= Configure Byteman for Use with the Quickstarts

[[configure_byteman_for_use_with_the_quickstarts_summary]]
== Summary

_Byteman_ is a tool that simplifies tracing and testing of Java programs. It allows you to insert extra Java code into your application, either as it is loaded during JVM startup or after it has already started running. This code can be used to trace what the application is doing and to monitor and debug deployments to be sure it is operating correctly. You can also use _Byteman_ to inject faults or synchronization code when testing your application.

A few of the quickstarts use _Byteman_ to demonstrate distributed transaction processing and crash recovery, for example, to halt an application server in the middle of a distributed transaction to demonstrate crash recovery.

The following sections describe the steps necessary to install, configure, and use _Byteman_ with these quickstarts.

* xref:download_and_configure_byteman[Download and Configure Byteman]
* xref:clear_the_transaction_objectstore[Clear the Transaction ObjectStore]
* xref:use_byteman_to_halt_the_application[Use Byteman to Halt the Application]
* xref:disable_the_byteman_script[Disable the Byteman Script]

NOTE: See link:USE_OF_EAP_HOME.adoc[Use of EAP_HOME and JBOSS_HOME Variables] for information about the Red Hat JBoss Enterprise Application Platform installation path.

[[download_and_configure_byteman]]
== Download and Configure Byteman


. Download _Byteman_ from http://www.jboss.org/byteman/downloads/.
. Extract the ZIP file to a directory of your choice. In the instructions below, we refer to this directory as `__BYTEMAN_HOME__`.
. By default, the _Byteman_ download provides unrestricted permissions to `others` which can cause a problem when running Ruby commands for the OpenShift quickstarts. To restrict the permissions to `others`, open a terminal and type the following:
+
[source,subs="+quotes",options="nowrap"]
----
$ chmod -R o-rwx __BYTEMAN_HOME__/
----

[[clear_the_transaction_objectstore]]
== Clear the Transaction ObjectStore

Transaction objectstore data remaining from previous tests can prevent _Byteman_ from working properly. You must remove any remaining data before running new _Byteman_ tests.  If you are using the default file based transaction logging store:

. Open a terminal and type the following:
+
[source,subs="+quotes",options="nowrap"]
----
$ ls __EAP_HOME__/standalone/data/tx-object-store/ShadowNoFileLockStore/defaultStore/StateManager/BasicAction/TwoPhaseCoordinator/AtomicAction/
----

. If this directory exists and contains any files, delete them before starting the server:
+
[source,subs="+quotes",options="nowrap"]
----
$ rm -rf __EAP_HOME__/standalone/data/tx-object-store/ShadowNoFileLockStore/defaultStore/StateManager/BasicAction/TwoPhaseCoordinator/AtomicAction/*
----
. On Windows, use the file manager to accomplish the same result.

[[use_byteman_to_halt_the_application]]
== Use Byteman to Halt the Application

NOTE: The _Byteman_ scripts only work in JTA mode. They do not work in JTS mode. If you have configured the server for a quickstart that uses JTS, you must follow the quickstart instructions to remove the JTS configuration from the JBoss EAP server before making the following changes. Otherwise _Byteman_ will not halt the server.

When instructed to use _Byteman_ to halt the application, perform the following steps:

. Find the appropriate configuration file for your operating system in the list below.

* For Linux: `__EAP_HOME__/bin/standalone.conf`
* For Windows: `__EAP_HOME__\bin\standalone.conf.bat`

[[important_make_a_backup_copy]]

. **Important**: Make a backup copy of this configuration file before making any modifications!
. Open the configuration file and append the text specified in the quickstart `README` file  instructions to the end of the configuration file. Be sure to replace the `__BYTEMAN_HOME__` with the path to the Byteman download and the `__QUICKSTART_HOME__` with the path to the quickstarts.
+
The following is an example of of the configuration changes needed for the _jta-crash-rec_ quickstart.

* For Linux:
+
[source,subs="+quotes",options="nowrap"]
----
JAVA_OPTS="-javaagent:/__BYTEMAN_HOME__/lib/byteman.jar=script:/__QUICKSTART_HOME__/jta-crash-rec/src/main/scripts/xa.btm ${JAVA_OPTS}"
----
* For Windows:
+
[source,subs="+quotes",options="nowrap"]
----
SET "JAVA_OPTS=%JAVA_OPTS% -javaagent:C:\__BYTEMAN_HOME__\lib\byteman.jar=script:C:\__QUICKSTART_HOME__\jta-crash-rec\src\main\scripts\xa.btm %JAVA_OPTS%"
----

[[disable_the_byteman_script]]
== Disable the Byteman Script

When you have completed testing the quickstart, replace the server configuration file with the xref:important_make_a_backup_copy[backup copy] you created above to disable _Byteman_.

xref:configure_byteman_for_use_with_the_quickstarts[Back to top]
