[[create_users_required_by_the_quickstarts]]

= Create Users Required by the Quickstarts

== Summary

By default, Red Hat JBoss Enterprise Application Platform is distributed with security enabled for the management interfaces. A few of the quickstarts use these management interfaces and require that you create a management or application user to access the running application. An `add-user` script is provided in the `__EAP_HOME__/bin` directory for that purpose. You can run the script interactively or you can pass arguments on the command line.

NOTE: See link:USE_OF_EAP_HOME.adoc#use_of_product_home_and_jboss_home_variables[Use of EAP_HOME] for information about the JBoss EAP installation path.

The following procedures describe how to add a user with the appropriate permissions to run the quickstarts that depend on them.

* xref:add_a_management_user[Add a Management User]
* xref:add_an_application_user[Add an Application User]

Be aware that passwords must meet the following requirements:

* It can not be the same as the user name.
* It must contain at least 8 characters.
* It must contain at least one alphanumeric character.
* It must contain at least one digit.
* It must contain at least one non-alphanumeric symbol.

For more information about how to configure users, see the https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/[Product Documentation] for Red Hat JBoss Enterprise Application Platform.

[[add_a_management_user]]
== Add a Management User

You can pass arguments on the command line or you can run the script interactively. The examples below use "admin" for the `Username` and "adminPass1!" for the `Password`. If the quickstart requires a specific `Username` and `Password`, be sure to replace them in the examples below.

[[add_a_management_user_passing_arguments]]
=== Add a Management User Passing Arguments on the Command Line

You can create the management user non-interactively by passing each argument on the command line.

For example, to add the Management User `admin` in the default `ManagementRealm` realm with password `adminPass1!`,
open a terminal and type the following:

* For Linux: `$ __EAP_HOME__/bin/add-user.sh -u 'admin' -p 'adminPass1!'``
* For Windows: `> __EAP_HOME__\bin\add-user.bat -u 'admin' -p 'adminPass1!'``


[[add_a_management_user_interactively]]
=== Add a Management User Interactively

If you prefer, you can create the management user interactively.

. Open a terminal.
. Type the command for your operating system.
* For Linux: `$ __EAP_HOME__/bin/add-user.sh`
* For Windows: `> __EAP_HOME__\bin\add-user.bat`

. You should see the following response:
+
[source,options="nowrap"]
----
What type of user do you wish to add?

a) Management User (mgmt-users.properties)
b) Application User (application-users.properties)
(a):
----
+
. At the prompt, press enter to use the default `Management User`. You should see the following response.
+
[source,options="nowrap"]
----
Enter the details of the new user to add.
Using realm 'ManagementRealm' as discovered from the existing property files.
Username :
----
. Enter the `Username` and, at the next prompt, enter the `Password`.
+
[source,options="nowrap"]
----
Username : admin
Password : (choose a password for the admin user)
----
+
Repeat the password.
. At the next prompt, you are asked the following.
+
[source,options="nowrap"]
----
What groups do you want this user to belong to? (Please enter a comma separated list, or leave blank for none)[ ]:
----
+
Leave it blank and press enter.

. Choose `yes` for the remaining prompts.

[[add_an_application_user]]
== Add an Application User

You can pass arguments on the command line or you can run the script interactively. The examples below use "quickstartUser" for the `Username`, "quickstartPwd1!" for the `Password`, and "guest" for the group. If the quickstart requires a specific `Username`, `Password`, or `group`, be sure to replace them in the examples below.

[[add_an_application_user_passing_arguments]]
=== Add an Application User Passing Arguments on the Command Line

You can create the application user non-interactively by passing each argument on the command line.

The default application user for the quickstarts is `quickstartUser`, in the `ApplicationRealm` realm, with password `quickstartPwd1!`, and belonging to group `guest`.
To add the default application user, open a terminal and type the following:

* For Linux: `$ __EAP_HOME__/bin/add-user.sh -a -u 'quickstartUser' -p 'quickstartPwd1!' -g 'guest'`
* For Windows: `> __EAP_HOME__\bin\add-user.bat  -a -u 'quickstartUser' -p 'quickstartPwd1!' -g 'guest'`


[[add_an_application_user_interactively]]
=== Add an Application User Interactively

If you prefer, you can create the application user interactively.

. Open a terminal.
. Type the command for your operating system.

* For Linux: `$ __EAP_HOME__/bin/add-user.sh`
* For Windows: `> __EAP_HOME__\bin\add-user.bat`

. You should see the following response:
+
[source,options="nowrap"]
----
What type of user do you wish to add?

a) Management User (mgmt-users.properties)
b) Application User (application-users.properties)
(a):
----

. At the prompt, type  `b`. You should see the following response:
+
[source,options="nowrap"]
----
Enter the details of the new user to add.
Using realm 'ApplicationRealm' as discovered from the existing property files.
Username :
----

. Enter the the `Username` and at the next prompt, enter the `Password`. If the quickstart `_README_` file specifies a `Username` and `Password`, enter them here. Otherwise, use the default `Username` `quickstartUser` and `Password` `quickstartPwd1!`.
+
[source,options="nowrap"]
----
Username : quickstartUser
Password : quickstartPwd1!
----

. At the next prompt, you are asked the following.
+
[source,options="nowrap"]
----
What groups do you want this user to belong to? (Please enter a comma separated list, or leave blank for none)[  ]:
----

. If the quickstart `_README_` file specifies the groups to use, enter that here. Otherwise, type the group: `guest`

xref:create_users_required_by_the_quickstarts[Back to top]
