# Gemfile
source "https://rubygems.org"

# Platform helpers
def windows_only(require_as)
  RbConfig::CONFIG['host_os'] =~ /mingw|mswin/i ? require_as : false
end
def linux_only(require_as)
  RbConfig::CONFIG['host_os'] =~ /linux/ ? require_as : false
end
def darwin_only(require_as)
  RbConfig::CONFIG['host_os'] =~ /darwin/ ? require_as : false
end
 
# GEMS
gem 'tilt', '~> 2.0.0'
gem 'rake', '~> 10.0.4'


group :development do
  gem 'pry', require: false
  #gem 'pry-byebug', require: false
  #gem 'pry-stack_explorer', require: false
  #gem 'pry-exception_explorer', require: false
end

